
variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  only:
    refs:
      - develop
  script:
    - mvn $MAVEN_CLI_OPTS package
    - sudo docker build -t uhub.ucloud.cn/gary/hello-image:SNAP-$CI_JOB_ID .

buildToDeploy:
  stage: build
  only:
    - tags
    - master
  script:
    - mvn $MAVEN_CLI_OPTS package
    - sudo docker build -t uhub.ucloud.cn/gary/hello-image:$CI_COMMIT_TAG .

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test


deployToIntegration:
  only:
    refs:
      - develop
  stage: deploy
  script:
    - ssh root@k8s kubectl get pod -n kube-system

deployToPre:
  only:
    - tags
    - master
  stage: deploy
  script:
    - ssh root@k8s kubectl get pod

deployToProduct:
  only:
    - tags
    - master
  stage: deploy
  when: manual
  script:
    - ssh root@k8s kubectl get pod
