
variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

buildToIntegraion:
  stage: build
  only:
    refs:
      - develop
  script:
    - mvn $MAVEN_CLI_OPTS package
    - sudo docker build -t uhub.ucloud.cn/gary/hello-image:SNAP-$CI_PIPELINE_ID .


buildToDeploy:
  stage: build
  only:
    - tags
  script:
    - mvn $MAVEN_CLI_OPTS package
    - sudo docker build -t uhub.ucloud.cn/gary/hello-image:$CI_COMMIT_TAG .

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test


deployToIntegration:
  only:
    refs:
      - develop
  stage: deploy
  script:
    - sudo docker push uhub.ucloud.cn/gary/hello-image:SNAP-$CI_PIPELINE_ID
    - cat  yaml/hello_world_template.yaml |sed 's/<IMAGE_TAG>/SNAP-$CI_PIPELINE_ID/'  > /tmp/hello_world_SNAP-$CI_PIPELINE_ID.yaml
    - scp /tmp/hello_world_SNAP-$CI_JOB_ID.yaml root@k8s:/tmp/hello_world_SNAP-$CI_PIPELINE_ID.yaml
    - ssh root@k8s kubectl apply -f /tmp/hello_world_SNAP-$CI_PIPELINE_ID.yaml

deployToPre:
  only:
    - tags
  stage: deploy
  script:
    - ssh root@k8s kubectl get pod

deployToProduct:
  only:
    - tags
  stage: deploy
  when: manual
  script:
    - ssh root@k8s kubectl get pod
