apiVersion: v1
kind: Pod
metadata:
  name: garyhelloworld
  labels:
     app: helloapp
spec:
  containers:
    - name: helloappc
      image: uhub.ucloud.cn/gary/hello-image:<IMAGE_TAG>
      ports:
      - containerPort: 8080
        protocol: TCP
  imagePullSecrets:
    - name: garynexusin
